[package]
name = "radmin-router"
version = "0.1.1"
edition = "2024"

[dependencies]
bytes = "1"
http-body-util = "0"
hyper = "1"
macros = { path = "macros" }
futures = "0"
chrono = { version = "0", optional = true }

[features]
default = []
logging = ["dep:chrono"]
